# Generated by Django 4.2 on 2023-04-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Active"), (1, "Inactive")], default=0
                    ),
                ),
                ("category_name", models.CharField(max_length=30)),
                ("user_token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.TextField(blank=True, null=True)),
                ("updated_by", models.TextField(blank=True, null=True)),
                (
                    "is_global",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
    ]
