# Generated by Django 4.2 on 2023-06-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_usertoken_alter_apidata_options_and_more'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='category',
            name='user_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_token_category', to='api_data.usertoken'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
