# Generated by Django 4.2 on 2023-04-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_token", models.TextField()),
                ("api_token", models.TextField()),
                ("url", models.CharField(max_length=1024)),
                (
                    "method",
                    models.IntegerField(
                        choices=[(1, "Get"), (2, "Post"), (3, "Put"), (4, "Delete")],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Active"), (1, "Inactive")], default=0
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApiResponses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("body", models.JSONField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Active"), (1, "Inactive")], default=0
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_settings.responsecodes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApiDataResponses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_response",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "api_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_data.apidata",
                    ),
                ),
                (
                    "api_response",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_data.apiresponses",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="apidata",
            name="Responses",
            field=models.ManyToManyField(
                through="api_data.ApiDataResponses", to="api_data.apiresponses"
            ),
        ),
        migrations.AddField(
            model_name="apidata",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="category.category",
            ),
        ),
    ]
