# Generated by Django 4.2 on 2023-06-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_token', models.TextField()),
                ('api_token', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_token',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='apidata',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='apidata',
            old_name='Responses',
            new_name='responses',
        ),
        migrations.RemoveField(
            model_name='apidata',
            name='api_token',
        ),
        migrations.AlterModelTable(
            name='apidata',
            table='api_data',
        ),
        migrations.AlterField(
            model_name='apidata',
            name='user_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_token_api_data', to='api_data.usertoken'),
        ),
    ]
