# Generated by Django 4.2 on 2023-06-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_data', '0002_usertoken_alter_apidata_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='apiresponses',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
